//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class D_Build
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public int LayerCount { get; set; }
        public int ReceiveNumber { get; set; }
        public Nullable<int> InNumber { get; set; }
        public string Property { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string AddUserId { get; set; }
        public string EditUserId { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public bool IsDelete { get; set; }
        public int Sort { get; set; }
        public string Remark { get; set; }
    }
}
