//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_SeeCharge
    {
        public string SeeChargeID { get; set; }
        public string SeeCharge_MenuID { get; set; }
        public string SeeCharge_Name { get; set; }
        public string SeeCharge_Code { get; set; }
        public Nullable<int> SeeCharge_Sort { get; set; }
        public Nullable<System.DateTime> SeeCharge_AddTime { get; set; }
    }
}
