//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Notice
    {
        public string NoticeID { get; set; }
        public string Notice_Type { get; set; }
        public string Notice_Title { get; set; }
        public string Notice_Content { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string AddUserId { get; set; }
        public string EditUserId { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public bool IsDelete { get; set; }
        public int Sort { get; set; }
        public string Notice_Scope { get; set; }
    }
}
