//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Post
    {
        public string PostID { get; set; }
        public string Post_Name { get; set; }
        public string Post_DepCode { get; set; }
        public Nullable<System.DateTime> Post_AddTime { get; set; }
        public string Post_AddUserId { get; set; }
        public string Post_EditUserId { get; set; }
        public Nullable<System.DateTime> Post_EditTime { get; set; }
        public bool Post_IsDelete { get; set; }
        public int Post_Sort { get; set; }
    }
}
