//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_MenuOperatingButton
    {
        public string Id { get; set; }
        public string MenuId { get; set; }
        public string Name { get; set; }
        public string Marker { get; set; }
        public string IconName { get; set; }
        public string Icon { get; set; }
        public string Event { get; set; }
        public string Type { get; set; }
        public string EventType { get; set; }
        public string AddUserId { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string EditUserId { get; set; }
        public string EditTime { get; set; }
        public int Sort { get; set; }
        public string Remark { get; set; }
        public string Url { get; set; }
        public bool IsDelete { get; set; }
    
    	[JsonIgnore]
        public virtual Sys_Menu Sys_Menu { get; set; }
    }
}
