//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Setting
    {
        public string SettingID { get; set; }
        public string Setting_Key { get; set; }
        public string Setting_Value { get; set; }
        public string Setting_Name { get; set; }
        public string Setting_Remarks { get; set; }
        public Nullable<int> Setting_ValueType { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string AddUserId { get; set; }
        public string EditUserId { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public bool IsDelete { get; set; }
        public int Sort { get; set; }
    }
}
