//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Role
    {
        public string RoleID { get; set; }
        public string Role_Name { get; set; }
        public string Role_Description { get; set; }
        public Nullable<int> Role_Sequence { get; set; }
        public string Role_IsDel { get; set; }
        public Nullable<System.DateTime> Role_AddTime { get; set; }
        public string Role_AddUserID { get; set; }
        public Nullable<int> Role_ShowType { get; set; }
    }
}
