//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_RolePurview
    {
        public string RolePurviewID { get; set; }
        public string RolePurview_RoleID { get; set; }
        public string RolePurview_MenuCode { get; set; }
        public string RolePurview_OperatePurview { get; set; }
        public string RolePurview_SeeCharge { get; set; }
        public string RolePurview_SeeDepCode { get; set; }
        public string RolePurview_SeeType { get; set; }
    }
}
