//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_UserInfo
    {
        public string UserInfoID { get; set; }
        public string UserInfo_RoleID { get; set; }
        public string UserInfo_Post { get; set; }
        public string UserInfo_FullName { get; set; }
        public string UserInfo_Sex { get; set; }
        public Nullable<System.DateTime> UserInfo_DateBirth { get; set; }
        public Nullable<int> UserInfo_Age { get; set; }
        public string UserInfo_DepCode { get; set; }
        public string UserInfo_Hometown { get; set; }
        public string UserInfo_Schools { get; set; }
        public string UserInfo_Specialty { get; set; }
        public string UserInfo_OccupTitle { get; set; }
        public string UserInfo_Position { get; set; }
        public string UserInfo_PositionLevel { get; set; }
        public Nullable<System.DateTime> UserInfo_NowHoldPostTime { get; set; }
        public string UserInfo_EduBackground { get; set; }
        public string UserInfo_PoliticalLandscape { get; set; }
        public string UserInfo_PhoneNumber { get; set; }
        public string UserInfo_IdentityCred { get; set; }
        public string UserInfo_Address { get; set; }
        public string UserInfo_Nation { get; set; }
        public string UserInfo_NationName { get; set; }
        public Nullable<System.DateTime> UserInfo_JoinPartyDate { get; set; }
        public Nullable<System.DateTime> UserInfo_EnlistTime { get; set; }
        public string UserInfo_Badge { get; set; }
        public string UserInfo_EnlistPlace { get; set; }
        public Nullable<System.DateTime> UserInfo_StartWorkDate { get; set; }
        public string UserInfo_EducationalLevel { get; set; }
        public string UserInfo_EducationalLevelName { get; set; }
        public string UserInfo_LoginUserName { get; set; }
        public string UserInfo_LoginUserPwd { get; set; }
        public string UserInfo_AddUserID { get; set; }
        public Nullable<System.DateTime> UserInfo_AddTime { get; set; }
        public string UserInfo_Status { get; set; }
        public string UserInfo_Type { get; set; }
        public Nullable<int> UserInfo_Sequence { get; set; }
        public string UserInfo_WorkingState { get; set; }
        public Nullable<bool> UserInfo_IsDelete { get; set; }
        public Nullable<System.DateTime> UserInfo_EditTime { get; set; }
        public string UserInfo_EditUserId { get; set; }
    }
}
