//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_DataDict
    {
        public string DataDictID { get; set; }
        public string DataDict_Name { get; set; }
        public string DataDict_Code { get; set; }
        public string DataDict_ParentCode { get; set; }
        public string DataDict_ParentPath { get; set; }
        public string DataDict_TopId { get; set; }
        public Nullable<bool> DataDict_IsChild { get; set; }
        public int DataDict_Sequence { get; set; }
        public string DataDict_Remark { get; set; }
        public Nullable<int> DataDict_Level { get; set; }
        public System.DateTime DataDict_AddTime { get; set; }
        public string DataDict_AddUserID { get; set; }
        public bool DataDict_IsDel { get; set; }
    }
}
