//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ModelFile
    {
        public string FileID { get; set; }
        public string File_Name { get; set; }
        public string File_Extension { get; set; }
        public Nullable<decimal> File_Size { get; set; }
        public string File_Type { get; set; }
        public string File_Path { get; set; }
        public Nullable<System.DateTime> File_AddTime { get; set; }
        public string File_OperationID { get; set; }
        public string File_UserID { get; set; }
        public Nullable<int> File_Sort { get; set; }
    }
}
