//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Desktop
    {
        public string DesktopID { get; set; }
        public string Desktop_UserInfoID { get; set; }
        public string Desktop_MenuID { get; set; }
        public string Desktop_Icon { get; set; }
        public string Desktop_Name { get; set; }
        public int Desktop_Sort { get; set; }
        public Nullable<System.DateTime> Desktop_AddTime { get; set; }
        public Nullable<System.DateTime> Desktop_EditTime { get; set; }
        public string Desktop_TabType { get; set; }
        public string Desktop_Type { get; set; }
    }
}
