//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Area
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ParentId { get; set; }
        public int Depth { get; set; }
        public int Sort { get; set; }
        public string Path { get; set; }
        public string PostCode { get; set; }
        public string AreaCode { get; set; }
        public string PinYin { get; set; }
        public Nullable<int> CrossArea { get; set; }
    }
}
