//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_PostChange
    {
        public string PostChangeID { get; set; }
        public string PostChange_ChangeUserID { get; set; }
        public string PostChange_BeforeChangeDep { get; set; }
        public string PostChange_BeforeChangePost { get; set; }
        public string PostChange_AfterChangeDep { get; set; }
        public string PostChange_AfterChangePost { get; set; }
        public System.DateTime PostChange_ChangeTime { get; set; }
        public string PostChange_OperateUserID { get; set; }
    }
}
