//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Jalendar
    {
        public string JalendarID { get; set; }
        public string Jalendar_Event { get; set; }
        public string Jalendar_Type { get; set; }
        public Nullable<System.DateTime> Jalendar_StartDate { get; set; }
        public Nullable<System.DateTime> Jalendar_EndDate { get; set; }
        public string Jalendar_EventStatus { get; set; }
        public string Jalendar_AddUserID { get; set; }
        public Nullable<System.DateTime> Jalendar_AddTime { get; set; }
    }
}
