//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_PendingMatter
    {
        public string PendingMatterID { get; set; }
        public string PendingMatter_ModuleID { get; set; }
        public string PendingMatter_ModuleName { get; set; }
        public string PendingMatter_Title { get; set; }
        public string PendingMatter_ToRoleName { get; set; }
        public string PendingMatter_URL { get; set; }
        public Nullable<System.DateTime> PendingMatter_AddTime { get; set; }
        public string PendingMatter_AddUserID { get; set; }
    }
}
