//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_UploadDataType
    {
        public string UploadDataType_ID { get; set; }
        public string UploadDataType_ProductType { get; set; }
        public string UploadDataType_ProcessStage { get; set; }
        public string UploadDataType_TypeCode { get; set; }
        public string UploadDataType_Name { get; set; }
        public string UploadDataType_DataType { get; set; }
        public string UploadDataType_Remark { get; set; }
        public Nullable<int> UploadDataType_SortNo { get; set; }
        public Nullable<bool> UploadDataType_IsDelete { get; set; }
    }
}
