//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class View_Workflow_NodeCondition
    {
        public string TasksEx_Name { get; set; }
        public string NodeConfigEx_Name { get; set; }
        public string NextWfNodeName { get; set; }
        public string NodeConditionID { get; set; }
        public string NodeCondition_WfConfigNodeID { get; set; }
        public string NodeCondition_Description { get; set; }
        public string NodeCondition_Content { get; set; }
        public string NodeCondition_ParameterType { get; set; }
        public Nullable<double> NodeCondition_ParameterStart { get; set; }
        public Nullable<double> NodeCondition_ParameterEnd { get; set; }
        public string NodeCondition_FixedParameter { get; set; }
        public string NodeCondition_FixedParameterType { get; set; }
        public string NodeCondition_NextWfConfigNodeID { get; set; }
        public string NodeCondition_UpdateUserID { get; set; }
        public Nullable<System.DateTime> NodeCondition_UpdateTime { get; set; }
        public Nullable<bool> NodeCondition_IsDeleted { get; set; }
        public string NodeConfigExID { get; set; }
        public string NodeConfigEx_TasksInstanceID { get; set; }
        public string NodeConfigEx_NodeSign { get; set; }
        public Nullable<int> NodeConfigEx_Setp { get; set; }
        public string Expr2 { get; set; }
        public string NodeConfigEx_AuditMode { get; set; }
        public string NodeConfigEx_AuditObjectID { get; set; }
        public Nullable<int> NodeConfigEx_Mechanism { get; set; }
        public string NodeConfigEx_DistributionRule { get; set; }
        public string NodeConfigEx_UpdateUserID { get; set; }
        public Nullable<System.DateTime> NodeConfigEx_UpdateTime { get; set; }
        public Nullable<bool> NodeConfigEx_IsDeleted { get; set; }
        public string TasksEx_InstanceID { get; set; }
        public string TasksEx_InstanceNo { get; set; }
        public string TasksEx_Type { get; set; }
        public string TasksEx_InstanceVerNo { get; set; }
        public string Expr3 { get; set; }
        public Nullable<bool> TasksEx_IsValid { get; set; }
        public string TasksEx_AddUserID { get; set; }
        public Nullable<System.DateTime> TasksEx_AddTime { get; set; }
        public Nullable<bool> TasksEx_IsDeleted { get; set; }
        public string Expr4 { get; set; }
        public string Expr5 { get; set; }
        public string Expr6 { get; set; }
        public Nullable<int> Expr7 { get; set; }
        public string Expr8 { get; set; }
        public string Expr9 { get; set; }
        public string Expr10 { get; set; }
        public Nullable<int> Expr11 { get; set; }
        public string Expr12 { get; set; }
        public string Expr13 { get; set; }
        public Nullable<System.DateTime> Expr14 { get; set; }
        public Nullable<bool> Expr15 { get; set; }
    }
}
