//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class View_Workflow_NodeBusiEx
    {
        public string NodeBusiExID { get; set; }
        public string NodeBusiEx_ModuleID { get; set; }
        public string NodeBusiEx_TasksInstanceID { get; set; }
        public string NodeBusiEx_LastWfConfigNodeID { get; set; }
        public string NodeBusiEx_LastNodeBusiExID { get; set; }
        public string NodeBusiEx_WorkflowNodeConfigID { get; set; }
        public Nullable<int> NodeBusiEx_Setp { get; set; }
        public Nullable<bool> NodeBusiEx_IfCurrSetp { get; set; }
        public string NodeBusiEx_Status { get; set; }
        public Nullable<System.DateTime> NodeBusiEx_AppendTime { get; set; }
        public string NodeBusiEx_WfAuditActionDefinitionID { get; set; }
        public string NodeBusiEx_AuditOpinion { get; set; }
        public string NodeBusiEx_OutsideOpinions { get; set; }
        public string NodeBusiEx_AuditUserID { get; set; }
        public Nullable<System.DateTime> NodeBusiEx_AuditTime { get; set; }
        public string NodeBusiEx_State { get; set; }
        public Nullable<bool> NodeBusiEx_IsDeleted { get; set; }
        public string UserInfo_FullName { get; set; }
        public string AuditActionDefinition_Name { get; set; }
    }
}
