//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class View_Workflow_NodeConfigEx
    {
        public string NodeBusiEx_ModuleID { get; set; }
        public string NodeConfigExID { get; set; }
        public string NodeConfigEx_TasksInstanceID { get; set; }
        public string NodeConfigEx_NodeSign { get; set; }
        public Nullable<int> NodeConfigEx_Setp { get; set; }
        public string NodeConfigEx_Name { get; set; }
        public string NodeConfigEx_AuditMode { get; set; }
        public string NodeConfigEx_AuditObjectID { get; set; }
        public Nullable<int> NodeConfigEx_Mechanism { get; set; }
        public string NodeConfigEx_DistributionRule { get; set; }
        public string NodeConfigEx_UpdateUserID { get; set; }
        public Nullable<System.DateTime> NodeConfigEx_UpdateTime { get; set; }
        public Nullable<bool> NodeConfigEx_IsDeleted { get; set; }
        public Nullable<bool> NodeConfigEx_IsDisplayContract { get; set; }
        public string NodeConfigEx_DataMappingID { get; set; }
    }
}
