//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class View_Sys_UserInfo
    {
        public string UserInfoID { get; set; }
        public string UserInfo_RoleID { get; set; }
        public string UserInfo_Post { get; set; }
        public string UserInfo_FullName { get; set; }
        public string UserInfo_Sex { get; set; }
        public Nullable<System.DateTime> UserInfo_DateBirth { get; set; }
        public Nullable<int> UserInfo_Age { get; set; }
        public string UserInfo_DepCode { get; set; }
        public string UserInfo_Hometown { get; set; }
        public string UserInfo_Schools { get; set; }
        public string UserInfo_Specialty { get; set; }
        public string UserInfo_OccupTitle { get; set; }
        public string UserInfo_Position { get; set; }
        public string UserInfo_PositionLevel { get; set; }
        public Nullable<System.DateTime> UserInfo_NowHoldPostTime { get; set; }
        public string UserInfo_EduBackground { get; set; }
        public string UserInfo_PoliticalLandscape { get; set; }
        public string UserInfo_PhoneNumber { get; set; }
        public string UserInfo_IdentityCred { get; set; }
        public string UserInfo_Address { get; set; }
        public string UserInfo_LoginUserName { get; set; }
        public string UserInfo_LoginUserPwd { get; set; }
        public Nullable<System.DateTime> UserInfo_AddTime { get; set; }
        public string Department_Name { get; set; }
        public Nullable<int> Department_Sequence { get; set; }
        public string Department_Respon { get; set; }
        public string Department_ParentCode { get; set; }
        public Nullable<int> Department_Level { get; set; }
        public string Department_IsDel { get; set; }
        public System.DateTime Department_AddTime { get; set; }
        public string UserInfo_RoleName { get; set; }
        public string UserInfo_PostName { get; set; }
        public string UserInfo_Status { get; set; }
        public string UserInfo_Type { get; set; }
        public Nullable<int> UserInfo_Sequence { get; set; }
        public Nullable<int> UserInfo_PostSequence { get; set; }
        public string UserInfo_StatusName { get; set; }
        public string UserInfo_Nation { get; set; }
        public Nullable<System.DateTime> UserInfo_StartWorkDate { get; set; }
        public string UserInfo_EducationalLevel { get; set; }
        public Nullable<System.DateTime> UserInfo_JoinPartyDate { get; set; }
        public string Department_Type { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public Nullable<System.DateTime> UserInfo_EnlistTime { get; set; }
        public string UserInfo_Badge { get; set; }
        public string UserInfo_EnlistPlace { get; set; }
        public string DepartmentID { get; set; }
        public string UserInfo_WorkingState { get; set; }
        public Nullable<bool> UserInfo_IsDelete { get; set; }
    }
}
