//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class View_Workflow_RoleAACTDefinition
    {
        public string RoleAACTDefinitionID { get; set; }
        public string RoleAACTDefinition_RoleID { get; set; }
        public string RoleAACTDefinition_DefinitionID { get; set; }
        public string AuditActionDefinition_Name { get; set; }
        public Nullable<bool> AuditActionDefinition_IsStartWF { get; set; }
        public string RoleAACTDefinition_InstanceID { get; set; }
    }
}
