//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow_NodeCondition
    {
        public string NodeConditionID { get; set; }
        public string NodeCondition_WfConfigNodeID { get; set; }
        public string NodeCondition_Description { get; set; }
        public string NodeCondition_Content { get; set; }
        public string NodeCondition_ParameterType { get; set; }
        public Nullable<double> NodeCondition_ParameterStart { get; set; }
        public Nullable<double> NodeCondition_ParameterEnd { get; set; }
        public string NodeCondition_FixedParameter { get; set; }
        public string NodeCondition_FixedParameterType { get; set; }
        public string NodeCondition_NextWfConfigNodeID { get; set; }
        public string NodeCondition_NextWfOptionURL { get; set; }
        public string NodeCondition_UpdateUserID { get; set; }
        public Nullable<System.DateTime> NodeCondition_UpdateTime { get; set; }
        public Nullable<bool> NodeCondition_IsDeleted { get; set; }
    }
}
