//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow_NodeRoute
    {
        public string NodeRouteID { get; set; }
        public string NodeRoute_WfConfigNodeID { get; set; }
        public string NodeRoute_WfAuditActionDefinitionID { get; set; }
        public Nullable<bool> NodeRoute_IfCondJump { get; set; }
        public string NodeRoute_NextWfConfigNodeID { get; set; }
        public string NodeRoute_NextWfOptionURL { get; set; }
        public Nullable<int> NodeRoute_NextWfOptionUserAttribute { get; set; }
        public string NodeRoute_UpdateUserID { get; set; }
        public Nullable<System.DateTime> NodeRoute_UpdateTime { get; set; }
        public Nullable<bool> NodeRoute_IsDeleted { get; set; }
    }
}
