//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow_TasksEx
    {
        public string TasksEx_InstanceID { get; set; }
        public string TasksEx_InstanceNo { get; set; }
        public string TasksEx_Type { get; set; }
        public string TasksEx_InstanceVerNo { get; set; }
        public string TasksEx_Name { get; set; }
        public Nullable<bool> TasksEx_IsValid { get; set; }
        public string TasksEx_AddUserID { get; set; }
        public Nullable<System.DateTime> TasksEx_AddTime { get; set; }
        public Nullable<bool> TasksEx_IsDeleted { get; set; }
    }
}
